server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderItemdb
    username: root
    password: root@0902
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
