server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockMovementdb
    username: root
    password: root@0902
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
